### ISSUE TITLE
Missing examples on how to add Query Params when using the HTTP Outbound Endpoint

### ISSUE THREAD

**Issue by adrianpineyro** [mulesoft/mulesoft-docs#922]
On the following doc:

mulesoft-docs/mule-user-guide/v/3.6/http-transport-reference.adoc

There is no example on how to add/send query params when using the HTTP Outbound Endpoint.

Thanks!

**Comment by fermujica** [comment]
Is there any difference with the [Including Custom Header Properties](https://docs.mulesoft.com/mule-user-guide/v/3.6/http-transport-reference#including-custom-header-properties) section there ?
Any specific use case we should consider? 

Since the HTTP Outbound Endpoint is replaced by the HTTP Connector we don't review these docs that often, but if there are any useful use cases or practices that we are not seeing, I could even add those in the [HTTP Requester](https://docs.mulesoft.com/mule-user-guide/v/3.8/http-request-connector#headers) docs as well.
